<?php
// module/Categories/view/category/category/add.phtml:

$title = 'Edit product';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php
$form->setAttribute('action', $this->url('products', ['action' => 'edit']));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('Id'));
echo $this->formRow($form->get('Name'));
echo $this->formRow($form->get('Size'));
echo $this->formRow($form->get('Color'));
echo $this->formRow($form->get('Price'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();