<?php
// module/Users/view/category/category/add.phtml:

$title = 'Edit current user';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<?php
$form->setAttribute('action', $this->url('users', ['action' => 'edit']));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('Name'));
echo $this->formRow($form->get('Telephone'));
echo $this->formRow($form->get('Email'));
echo $this->formRow($form->get('Password'));
echo $this->formRow($form->get('RoleId'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();