<?php
// module/category/view/category/category/index.phtml:

$title = 'My Categories';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    <a class="label label-success" href="<?= $this->url('categories', ['action' => 'add']) ?>">Add new category</a>
</p>

<table class="table table-hover">
<thead>
<tr>
    <th scope="col">Name</th>
    <th scope="col">Actions</th>
</tr>
</thead>
<tbody>
<?php foreach ($categories as $category) : ?>
    <tr class="table-info">
        <td><?= $this->escapeHtml($category->categoryName) ?></td>
        <td>
        <a class="label label-info" href="<?php echo $this->url('categories',
             array('action'=>'edit', 'id' => $category->id));?>">Edit</a>
         <a class="label label-danger" href="<?php echo $this->url('categories',
             array('action'=>'delete', 'id' => $category->id));?>">Delete</a>
        </td>
    </tr>
<?php endforeach; ?>
</tbody>
</table>